name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.11.1
      - uses: actions/setup-node@v3
        with:
          node-version: 22.10.0
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
